### ISSUE TITLE
KMODE_EXCEPTION_NOT_HANDLED on windows 8 and driver wont start

### ISSUE THREAD

**Issue by Keyz55** [hfiref0x/TDL#1]

**Comment by hfiref0x** [comment]
Hello.
You won't see anything in ProcessHacker2, it is not designed to display this kind of code. 
Your drivers will not load properly if they are not coded as driverless. As for DbgView - it is Mark's fault, sometimes his tool unable to output debug messages from it internal buffer. At entry point of example driver - create some named mutex or event, so you will see if driver loaded or not.

**Comment by Keyz55** [comment]
Hi,

Alright thanks for the info. Also, can you explain me what you mean by "driverless"?
And yeah on DbgView I see this line "[7860] SHIMVIEW: ShimInfo(Complete) " just after I load a dummy driver. I guess that's it.

Also, what should I do to make my drivers compatible with your software? What kind of change should I make?

Thanks,

**Comment by hfiref0x** [comment]
"[7860] SHIMVIEW: ShimInfo(Complete) " this is likely from explorer.exe
Driverless mean this driver will not be loaded as "driver" but as code buffer. Which automatically mean that parameters on the DriverEntry(DriverObject, RegistryPath) will be invalid and should not be used. Your driver will not be attached to driver list, so SEH will not work in your code. Driver unload is also impossible. See DummyDrv2 for example.

**Comment by Keyz55** [comment]
Alright i'm able to load perfectly fine both dummy's drivers but I still crash when I load my custom driver.
I tried to make some changes like removing DriverEntry calls but still bluescreen.
Here is my code if you can figure out what's wrong with : http://pastebin.com/siG7ZssJ

Thanks,

**Comment by hfiref0x** [comment]
Is it blue screens exactly with this code? You commented return from DriverMain btw.

If you uncomment this ->   

`status = IoCreateDriver(&drvName, &DriverInitialize);`

then this code 

 `RtlInitUnicodeString(&deviceNameUnicodeString, L"\\Device\\DRIVER");
    RtlInitUnicodeString(&deviceSymLinkUnicodeString, L"\\DosDevices\\DRIVER");
    IoCreateDevice(pDriverObject, 0, &deviceNameUnicodeString, FILE_DEVICE_UNKNOWN, FILE_DEVICE_UNKNOWN, FALSE, &Global);
    IoCreateSymbolicLink(&deviceSymLinkUnicodeString, &deviceNameUnicodeString);
    (*pDriverObject).DriverUnload = DriverExit;
    (*pDriverObject).MajorFunction[IRP_MJ_CLOSE] = CatchClose;
    (*pDriverObject).MajorFunction[IRP_MJ_CREATE] = CatchCreate;
    (*pDriverObject).MajorFunction[IRP_MJ_DEVICE_CONTROL] = RecievedIO;`

must be in DriverInitialize (where driver object will be parameter returned by IoCreateDriver) and this unlinking

`ModuleEntry = (PLDR_DATA_TABLE_ENTRY)(*pDriverObject).DriverSection;
    PrevEntry = (PLDR_DATA_TABLE_ENTRY)(*ModuleEntry).InLoadOrderLinks.Blink;
    NextEntry = (PLDR_DATA_TABLE_ENTRY)(*ModuleEntry).InLoadOrderLinks.Flink;
    (*PrevEntry).InLoadOrderLinks.Flink = (*ModuleEntry).InLoadOrderLinks.Flink;
    (*NextEntry).InLoadOrderLinks.Blink = (*ModuleEntry).InLoadOrderLinks.Blink;
    (*ModuleEntry).InLoadOrderLinks.Flink = (PLIST_ENTRY)ModuleEntry;
    (*ModuleEntry).InLoadOrderLinks.Blink = (PLIST_ENTRY)ModuleEntry;`

is no needed because drivers loaded by TDL not linked in any list.

**Comment by Keyz55** [comment]
Hi,

I'm not really sure why i'm getting this bluescreen (kernel_security_check_failure) I'm wondering if it could be an compiler option?

My code is similar to your and I copied pretty most functions from your dummy2 driver source

**Comment by hfiref0x** [comment]
Disable Security Check, /GS option C/C++ code generation. Look at DummyDrv2 settings.

**Comment by Keyz55** [comment]
Hey,

Thank you it's working fine :)
The only thing I dont understand it's when I try to change the drvname it result In a bluescreen:
WCHAR szDevName[] = { L'\\', L'D', L'e', L'v', L'i', L'c', L'e', L'\\', L'T', L'D', L'L', L'D', 0 };
Changed to "\\\\.\\DRIVER" to be able to communicate with.

Thanks again, awesome job!

**Comment by hfiref0x** [comment]
It is the name of Driver object. Yours "\\.\DRIVER" is a symbolic link.

In your case you need 
RtlInitUncodeString(&driverName, L"\\Driver\\YourDriverObjName");
IoCreateDriver(&driverName ...);

RtlInitUnicodeString(&deviceName, L"\\Device\\YourDeviceName");
IoCreateDevice(&deviceName... );

RtlInitUnicodeString(&symName, L"\\DosDevices\\YourSymbolicLinkName");
IoCreateSymbolicLink(&symName);
