### ISSUE TITLE
Vmprotect help

### ISSUE THREAD

**Issue by dummy0stud** [hfiref0x/TDL#11]
hey hfiref0x, awesome job, this is one of the most amazing loaders I have seen

I have a problem, I need to make tdl loader work with vmprotected driver, but it is crashing and as vmprotect do not have symbols, it becomes complicated to see where it is crashing and why(callstack does not give me much information)

Vmprotect is adding to driver IAT hal.dll(HalMakeBeep) dependency, can this be the root of the problem?

How can I get your knowledge? I wanna code/be like you, and can not see much information on the internet, can you link me your favorite books/tutorials?

Will SMEP protection catch this method?

**Comment by hfiref0x** [comment]
Hello,

all questions regarding third party software are not my business. I don't know how it work and what it want to work. As you said it rebuilds import table, so you need to resolve imports for HAL additionally to ntoskrnl. SMEP is for completely different story.
