### ISSUE TITLE
Unable to compile project

### ISSUE THREAD

**Issue by arpski** [hfiref0x/TDL#14]
Hi, i am unable to compile dummydrv2 and i need to compile it "as is" without touching anything.
VS2015, WDK10, Windows 7 x64.

When i try to compile it as it is, (windows 8.1, toolset 141, wkd10) it cannot find ntddk and stuff related to WDK 8.1, when i install WDK81 i cannot even load the project anymore.

Any idea?

**Comment by hfiref0x** [comment]
Use WDK 8.1 and Platform toolset WindowsKernelModeDriver8.1

**Comment by arpski** [comment]
"when i install WDK8.1 i cannot even load the project anymore."

**Comment by hfiref0x** [comment]
Do you understand how this is informative?

**Comment by arpski** [comment]
Well, if i install WDK 8.1 i cannot load or open the project anymore, thus i cannot compile the project with WindowsKernelModeDriver8.1, maybe i explained it little messed up.

**Comment by hfiref0x** [comment]
Redownload it. What VS is saying?

**Comment by arpski** [comment]
I have just uninstalled WDK81 and 10, installed WDK 81 again and i have still the same issue.

"C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Redirect.12.props(51,3): The imported project "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.cpp.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk."

I am using VS2015, AFAIK toolset120 is VS2013.

**Comment by hfiref0x** [comment]
Is recreating the project an option? I see some references to ToolsVersion="12.0" in dummy.vcxproj, you can try to change it, but I think recreating project is better.

C/C++ 
Optimization
Enable intrinsic Yes(/Oi)
Favor size or speed - favor fast code (/Ot)

Code generation
Disable Security Checks (/GS-)

Advanced
Compile as C (/TC)

Linker
Advanced Entry Point - DriverEntry
rest settings are insignificant.
