### ISSUE TITLE
BSOD @ Ldr: Resolving kernel import

### ISSUE THREAD

**Issue by ZirakC** [hfiref0x/TDL#2]
Hi,

I updated the DriverEntry and created DriverInitialize to match the Dummy.sys file, however whenever I use the loader to load my driver I end up blue screening at "Ldr: Resolving kernel import". Do you have any tips on checking what may be the cause for this blue screen?

Thanks!

**Comment by hfiref0x** [comment]
Show your code. "Ldr: Resolving kernel import" is in user mode, it cannot bsod.

**Comment by ZirakC** [comment]
http://pastebin.com/Sg7Da23v

Windows 10 x64 Version 1511 10586.104

**Comment by ZirakC** [comment]
Rewrote the driver using the Dummy2 source as base, eventually got it to work! Closing out ticket, thanks.
