### ISSUE TITLE
Something Wrong When I installed 2018 Jan Windows secuity patch

### ISSUE THREAD

**Issue by howknows** [hfiref0x/TDL#25]
2018 Jan ,I updated the newest Windows patch. It is used for patch Spectre and Meltdown vulnerabilities. But When I installed those pacthes ,this project will trigger a BSOD When I running "Furataka.exe dummy.sys" command.

**Comment by hfiref0x** [comment]
Do you expect this bugged oracle piece of shit driver be compatible with all patches and Windows versions until hmm... forever? And more important question what you want from me? Ask Oracle to give me updated 1.6 vbox driver with set of LPE that is compatible with Windows 10 RS4 and afterwards?
