### ISSUE TITLE
all kernelmodule

### ISSUE THREAD

**Issue by isdebug** [hfiref0x/TDL#26]
ULONG64 TDLGetProcAddressEx (_In_ char* DllName, _In_ char* FunctionName) {
    DPRINT ("                %s  %s\n", DllName, FunctionName);
    HMODULE temp = LoadLibraryExA (DllName, 0, DONT_RESOLVE_DLL_REFERENCES);
    ANSI_STRING    cStr;
    ULONG64      pfn = 0;
    RtlInitString (&cStr, FunctionName);
    if (!NT_SUCCESS (LdrGetProcedureAddress (temp, &cStr, 0, (PVOID*)&pfn))) {
        return 0;
    }
    return GetKMBase (DllName) + (pfn - (ULONG64)temp);
}
void TDLResolveKernelImport (_In_ ULONG_PTR Image, _In_ ULONG_PTR KernelImage, _In_ ULONG_PTR KernelBase) {
    PIMAGE_OPTIONAL_HEADER      popth;
    ULONG_PTR                   ITableVA, *nextthunk;
    PIMAGE_IMPORT_DESCRIPTOR    ITable;
    PIMAGE_THUNK_DATA           pthunk;
    PIMAGE_IMPORT_BY_NAME       pname;
    ULONG                       i;
    popth = &RtlImageNtHeader ((PVOID)Image)->OptionalHeader;
    if (popth->NumberOfRvaAndSizes <= IMAGE_DIRECTORY_ENTRY_IMPORT) {
        return;
    }
    ITableVA = popth->DataDirectory[IMAGE_DIRECTORY_ENTRY_IMPORT].VirtualAddress;
    if (ITableVA == 0) {
        return;
    }
	ITable = (PIMAGE_IMPORT_DESCRIPTOR)(Image + ITableVA);
    for (; ITable->Name; ++ITable) {
		if (ITable->OriginalFirstThunk == 0) {
			pthunk = (PIMAGE_THUNK_DATA)(Image + ITable->FirstThunk);
		}
		else {
			pthunk = (PIMAGE_THUNK_DATA)(Image + ITable->OriginalFirstThunk);
		}
		for (i = 0; pthunk->u1.Function != 0; i++, pthunk++) {
			nextthunk = (PULONG_PTR)(Image + ITable->FirstThunk);
			if ((pthunk->u1.Ordinal & IMAGE_ORDINAL_FLAG) == 0) {
				pname = (PIMAGE_IMPORT_BY_NAME)((PCHAR)Image + pthunk->u1.AddressOfData);
				nextthunk[i] = TDLGetProcAddressEx((char*)(Image + ITable->Name), pname->Name);
			}
			else {
				nextthunk[i] = TDLGetProcAddressEx((char*)(Image + ITable->Name), (char*)(pthunk->u1.Ordinal & 0xffff));
			}
		}
    }
   
   
}

**Comment by isdebug** [comment]
Furthermore, the driver entrance of the buffer loading is in the DISPATCH_LEVEL,It's not very comfortable. Do you have any good advice?

**Comment by hfiref0x** [comment]
Yes, don't use it.
