### ISSUE TITLE
BSOD After some ~ 30 Minutes

### ISSUE THREAD

**Issue by BlackSkill88** [hfiref0x/TDL#27]
I have a simple RPM and WPM Driver with Image Notify Routine and when i load it with TDL it works all fine... but after ~ 30 minutes my pc bluescreen. With normal Driver laoder it works without crash

Bluescreen Viewer:
042118-21765-01.dmp	21.04.2018 22:32:51		0x00000109	a39fdee6`1fd1b590	b3b6eb6c`72539df4	00000000`00000002	00000000`00000018	ntoskrnl.exe	ntoskrnl.exe+175930					x64	ntoskrnl.exe+175930					C:\Windows\Minidump\042118-21765-01.dmp	8	15	16299	1.192.684	21.04.2018 22:34:38

**Comment by hfiref0x** [comment]
This is normal behavior from PatchGuard on w10.

https://github.com/hfiref0x/UPGDSED/blob/master/src/tests/BadRkDemo/drv/dummy/main.c#L178

No workaround.
