### ISSUE TITLE
KMODE_EXCEPTION_NOT_HANDLED Windows 10

### ISSUE THREAD

**Issue by ZirakC** [hfiref0x/TDL#3]
Using the Dummy2 Driver Source code included within the solution, I added a couple functions taken from Black Bone Driver (COPY_MEM and ProtectMem) It seems like Copy Mem works fine, but whenever I call for ProtectMem I encounter a BSOD "KMODE_EXCEPTION_NOT_HANDLED".

This works fine if I load it through DSEFix on my other driver code (which is a full fledged driver).

I have attached the source with this ticket, wondering if you could help me identify what could be causing this?
[DummyDrv2.zip](https://github.com/hfiref0x/TDL/files/180999/DummyDrv2.zip)

**Comment by hfiref0x** [comment]
This is not TDL issue, debug it by commenting your code line by line. And all your SEH inside driver is not working.

**Comment by ZirakC** [comment]
Sorry, last question, you mentioned debug it by commenting my code line by line, would this mean to reboot my PC after each time I load the driver, as it cannot be unloaded on driverless mode?

Thanks,

**Comment by hfiref0x** [comment]
Yes. Make VM, connect windbg to it, put dbgprint everywhere and trace.
