### ISSUE TITLE
Error with LdrLoadDll

### ISSUE THREAD

**Issue by hsac1313** [hfiref0x/TDL#30]
C:\Users\hsac1\OneDrive\Desktop\TestKernel1\bin>TDL.exe Test.sys
Turla Driver Loader v1.1.4 started
(c) 2016 - 2019 TDL Project
Supported x64 OS : 7 and above

Ldr: Windows v10.0 build 14393
SCM: Vulnerable driver loaded and opened
Ldr: Kernel base = 0xFFFFF801BB292000
Ldr: Error while loading input driver file
SCM: Unloading vulnerable driver
SCM: Vulnerable driver successfully unloaded
SCM: Driver entry removed from registry
Ldr: Driver file removed

NTSTATUS = 0xC0000428

I could load the dummy.sys, but when I compiled own kernel and tried to load, always error raised.

**Comment by hfiref0x** [comment]
If dummy.sys is loaded and your file is not - it is obviously problem of your file. Probably you compiled it in a wrong way with wrong linker settings, something like integritycheck. Use dummy drivers as base for your code.

**Comment by hsac1313** [comment]
> If dummy.sys is loaded and your file is not - it is obviously problem of your file. Probably you compiled it in a wrong way with wrong linker settings, something like integritycheck. Use dummy drivers as base for your code.

OK, I'll check it. Thanks to your reply.
