### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by TheAifam5** [hfiref0x/TDL#8]
Hey, i have 2 questions about this TDL.
1. There is way to "manually" implement SEH to work with driverless drivers ? It is possible to do that? If yes, can u provide some good documentations?
2. It's possible to bypass PsSetCreateProcessNotifyRoutine (needs /INTEGRITYCHECK)

Regards,
TheAifam5

**Comment by hfiref0x** [comment]
Nothing from this are TDL issues. 1) No 2) PsSetCreateProcessNotifyRoutine does not need integrity check.

**Comment by TheAifam5** [comment]
so, maybe u know why on TDL PsSetCreateProcessNotifyRoutine returns 0xC0000022?
Looks like needs /INTEGRITYCHECK flag :/
Any way to bypass it?

I found in IDA that "PsSetCreateProcessNotifyRoutine" and "PsSetCreateProcessNotifyRoutineEx" are redirected to "PsSetCreateProcessNotifyRoutineEx2"...
"PsSetCreateProcessNotifyRoutineEx" needs integrity checks.
I think now on Windows 10 "PsSetCreateProcessNotifyRoutine" also needed.
