### ISSUE TITLE
No Longer Working

### ISSUE THREAD

**Issue by Zer0Mem0ry** [hfiref0x/TDL#9]
TDL Fails to load the driver on windows 10 OS Build 14393.187.
DebugViewer catches this:  EXWORKER: worker exit with system affinity set, worker routine FFFFF80057EAC6A0, parameter FFFFA08FC275B520, item FFFFA08FC275B520
However the driver works just fine if loaded by Win64ast.

These tests were ran using the already build drivers & Furutaka.

**Comment by Keyz55** [comment]
Hey, is that the newest Windows 10 version (anniversary) ?
